### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kpillis** [kpillis/tanfolyam2016-messageboard#1]
- [ ] Login form for client side authentication
- [ ] Remove name field from index.html
- [ ] Show name in comments
- [ ] Make api parameters required
- [ ] Input validation on server side
- [ ] Error handling on client side
- [ ] User can edit its post/comment
- [ ] User can delete its post/comment
- [ ] Logging on server side
- [ ] Error handling on server side
- [ ] Tests
- [ ] _User should only be able to like a post once_
- [ ] Update README.md
